#!/bin/bash

state=$(acpi | awk '{print $3}')
state=${state:0:-1}
percentage=$(acpi | awk '{print $4}')
time=$(acpi | awk '{print $5}')
need_color=0

result=""
if [[ ${state} == "Full" || ${state} == "Unknown" ]]; then
	percentage=${percentage:0:-1}
	result="${result} ${percentage}%"
else
	percentage=${percentage:0:-2}
	if [[ ${state} == "Charging" ]]; then
		result="${result}"
	elif [[ ${state} == "Discharging" ]]; then
		if [[ $percentage -ge 80 ]]; then
			result="${result}"
		elif [[ $percentage -ge 60 && $percentage -lt 80 ]]; then
			result="${result}"
		elif [[ $percentage -ge 40 && $percentage -lt 60 ]]; then
			result="${result}"
		elif [[ $percentage -ge 20 && $percentage -lt 40 ]]; then
			result="${result}"
		else
			result="${result}"
		fi
		need_color=1
	fi
	result="${result}  ${percentage}% ${time}"
fi

echo "${result}"
echo "${result}"
if [[ ${percentage} -le 15 && ! ${need_color} -eq 0 ]]; then
	echo \#F24152
fi
