#!/bin/bash

readarray response <<< "$(mpc status)"

if [[ ${#response[@]} -eq 3 ]]; then
	name=$(echo ${response[0]} | tr -d '\n')
	state=$(echo ${response[1]} | awk '{print $1}')
	state=${state:1:-1}
	progress=$(echo ${response[1]} | awk '{print $3}')
	if [[ ${state} == "playing" ]]; then
		echo " ${name} [${progress}]"
	else
		echo " ${name} [${progress}]"
	fi
fi
