#!/bin/bash

control="${BLOCK_INSTANCE:-$(amixer scontrols | sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" | head -n1)}"

capability() {
  amixer get ${control} | sed -n "s/  Capabilities:.*cvolume.*/Capture/p"
}

volume() {
  amixer get ${control} $(capability)
}

format() {
  perl_filter='if (/.*\[(\d+%)\] (\[(-?\d+.\d+dB)\] )?\[(on|off)\]/)'
  perl_filter+='{CORE::say $4 eq "off" ? "MUTE" : "'
  perl_filter+=$([[ $STEP = *dB ]] && echo '$3' || echo '$1')
  perl_filter+='"; exit}'
  perl -ne "$perl_filter"
}

result=$(volume | format)
if [[ ${result} == "MUTE" ]]; then
	echo -n " X"
else
	percentage=${result:0:-1}
	if [[ ${percentage} -ge 50 ]]; then
		echo -n ""
	else
		echo -n ""
	fi
	echo " ${result}"
fi
