#!/bin/bash

interface="${BLOCK_INSTANCE:-wlp2s0}"

echo -n " "

if [[ "$(cat /sys/class/net/$interface/operstate)" = 'down' ]]; then
	echo "down"
fi

echo $(grep $interface /proc/net/wireless | awk '{print int($3 * 100 / 70)"%"}')
