#!/bin/bash

if [[ -f /usr/share/bash-completion/bash_completion ]]; then
    source /usr/share/bash-completion/bash_completion
elif [[ -f /etc/bash/bashrc.d/bash_completion.sh ]]; then
    source /etc/bash/bashrc.d/bash_completion.sh
fi
