#!/bin/bash

use_color=false
if type -P dircolors >/dev/null ; then
    LS_COLORS=
    if [[ -f ~/.dir_colors ]] ; then
        used_default_dircolors="no"
        eval "$(dircolors -b ~/.dir_colors)"
    elif [[ -f /etc/DIR_COLORS ]] ; then
        used_default_dircolors="maybe"
        eval "$(dircolors -b /etc/DIR_COLORS)"
    else
        used_default_dircolors="yes"
        eval "$(dircolors -b)"
    fi
    if [[ -n ${LS_COLORS:+set} ]] ; then
        use_color=true

        case ${used_default_dircolors} in
        no) ;;
        yes) unset LS_COLORS ;;
        *)
            ls_colors=$(eval "$(dircolors -b)"; echo "${LS_COLORS}")
            if [[ ${ls_colors} == "${LS_COLORS}" ]] ; then
                unset LS_COLORS
            fi
            ;;
        esac
    fi
    unset used_default_dircolors
else
    case ${TERM} in
    [aEkx]term*|rxvt*|gnome*|konsole*|screen|cons25|*color) use_color=true;;
    esac
fi
