#!/bin/bash

# Enable checkwinsize so that bash will check the terminal size when it regains control.
shopt -s checkwinsize
# Disable completion when the input buffer is empty.  i.e. Hitting tab
# and waiting a long time for bash to expand all of $PATH.
shopt -s no_empty_cmd_completion
# append history entries
shopt -s histappend

# Set vi-mode
set -o vi
