#!/bin/bash

if [ -d "${HOME}/.ya.completion/bash/" ]; then
    for f in $(ls "${HOME}/.ya.completion/bash/"); do
        source "${HOME}/.ya.completion/bash/${f}";
    done;
fi

export ARCADIA_ROOT="${HOME}/arc/arcadia"
export YT_PROXY="hahn.yt.yandex.net"

alias ya="${ARCADIA_ROOT}/ya"
alias yql="ya yql"
alias yt="ya tool yt"
alias jq="ya tool jq"
