# Check shell interactivity
if [[ $- != *i* ]] ; then
    return
fi

source "${HOME}/.bash/colors"
source "${HOME}/.bash/detect_colors"
source "${HOME}/.bash/completion"
source "${HOME}/.bash/options"
source "${HOME}/.bash/alias"
source "${HOME}/.bash/export"
source "${HOME}/.bash/prompt"

if [[ -d "${HOME}/.bash/helpers/" ]]; then
    for f in $(ls "${HOME}/.bash/helpers/"); do
        source "${HOME}/.bash/helpers/${f}";
    done;
fi

source "${HOME}/.bash/yandex"
